[build]
  base = "docs/"
  publish = "build/"
  command = "npm run build"

[context.deploy-preview]
  base = "docs/"
  publish = "/"
  command = "yarn run previewBuild"
  [[redirects]]
    from = "/"
    to = "/docs"
